# Generated by Django 2.1.1 on 2018-09-27 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Year', models.CharField(blank=True, max_length=10)),
                ('Rated', models.CharField(blank=True, max_length=10)),
                ('Released', models.CharField(blank=True, max_length=20)),
                ('Runtime', models.CharField(blank=True, max_length=20)),
                ('Genre', models.CharField(blank=True, max_length=100)),
                ('Director', models.CharField(blank=True, max_length=100)),
                ('Writer', models.CharField(blank=True, max_length=200)),
                ('Actors', models.CharField(blank=True, max_length=500)),
                ('Plot', models.CharField(blank=True, max_length=500)),
                ('Language', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('Awards', models.CharField(blank=True, max_length=100)),
                ('Poster', models.CharField(blank=True, max_length=1000)),
                ('Metascore', models.CharField(blank=True, max_length=50)),
                ('imdbRating', models.CharField(blank=True, max_length=50)),
                ('imdbVotes', models.CharField(blank=True, max_length=50)),
                ('imdbID', models.CharField(blank=True, max_length=50)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('DVD', models.CharField(blank=True, max_length=50)),
                ('BoxOffice', models.CharField(blank=True, max_length=100)),
                ('Production', models.CharField(blank=True, max_length=100)),
                ('Website', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Films.Movie'),
        ),
    ]
